name: flowly
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://gitlab.com/jeanloth_projects/Flowly.git

environment:
  sdk: ^3.6.1

dependencies:
  firebase_core: 3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
